Create endpoint_classification
Open the paper "MobileNets: Efficient Convolutional Neural Networks for Mobile Vision Applications" (authored by Andrew G. Howard, Menglong Zhu, Bo Chen, Dmitry Kalenichenko, Weijun Wang, Tobias Weyand, Marco Andreetto, and Hartwig Adam) by clicking on Download: PDF in the top right corner of this website: https://arxiv.org/abs/1704.04861
Task requires a specific (fully convolutional) subset of MobileNets that we can re-use for our semantic segmentation task. Luckily, the creators provide us with a handy function for constructing custom MobileNets. During this lab, not all of the optional arguments are of importance, so the less relevant arguments are occluded and you will focus on the following three:

inputs
Of course, it is necessary to specify a tensor containing the image data in inputs so that the spatial dimensions can iteratively be adjusted from layer to layer (you can specify tensors of input sizes other than [ 224  x  224  x  3 ])

final_endpoint
The construction of our custom MobileNet instance will terminate at the layer with the string identifier final_endpoint. For instance, you could let your MobileNet creation stop after the first layer by filling in 'Conv2d_0', which is the only "classical" convolutional layer with kernel size  3  x  3  and a stride of  2 .

depth_multiplier
As described earlier, the parameter depth_multiplier dictates how many filters of the specified size are learned in all convolutional layers, and is therefore a useful measure to adjust the computational needs and the capacity of your network topology. By default, it is set to 1.0. In the first layer 'Conv2d_0', this default setting results in  32  filter maps. Lowering depth_multiplier to 0.5 for example, would reduce the number of filter maps to  16  for 'Conv2d_0'. This also reduces the layer's computational requirements as well as its capacity, and correspondingly halves all other convolution layers' number of filter maps.

Take a brief look at the reduced version of the TensorFlow function, and pay special attention to the options for final_endpoint:

def mobilenet_v1_base(inputs,
                      final_endpoint='TheLayerYouChoose',
                      depth_multiplier=1.0)
  """Mobilenet v1.

  Constructs a Mobilenet v1 network from inputs to the given final endpoint.

  Args:
    inputs: a tensor of shape [batch_size, height, width, channels].
    final_endpoint: specifies the endpoint to construct the network up to. It
      can be one of ['Conv2d_0', 'Conv2d_1_pointwise', 'Conv2d_2_pointwise',
      'Conv2d_3_pointwise', 'Conv2d_4_pointwise', 'Conv2d_5'_pointwise,
      'Conv2d_6_pointwise', 'Conv2d_7_pointwise', 'Conv2d_8_pointwise',
      'Conv2d_9_pointwise', 'Conv2d_10_pointwise', 'Conv2d_11_pointwise',
      'Conv2d_12_pointwise', 'Conv2d_13_pointwise'].
    depth_multiplier: Float multiplier for the depth (number of channels)
      for all convolution ops. The value must be greater than zero. Typical
      usage will be to set this value in (0, 1) to reduce the number of
      parameters or computation cost of the model.

  Returns:
    tensor_out: output tensor corresponding to the final_endpoint.
    end_points: a set of activations for external use, for example summaries or
                losses.

  Raises:
    ValueError: if final_endpoint is not set to one of the predefined values,
                or depth_multiplier <= 0, or the target output_stride is not
                allowed.
  """